# Generated by cpp11: do not edit by hand

sample_discrete_std_cpp <- function(n, prob_weights, random_seed) {
  .Call(`_cpp11rng_sample_discrete_std_cpp`, n, prob_weights, random_seed)
}

sample_discrete_boost_cpp <- function(n, prob_weights, random_seed) {
  .Call(`_cpp11rng_sample_discrete_boost_cpp`, n, prob_weights, random_seed)
}

sample_gamma_std_cpp <- function(n, shape, scale, random_seed) {
  .Call(`_cpp11rng_sample_gamma_std_cpp`, n, shape, scale, random_seed)
}

sample_gamma_boost_cpp <- function(n, shape, scale, random_seed) {
  .Call(`_cpp11rng_sample_gamma_boost_cpp`, n, shape, scale, random_seed)
}

sample_normal_std_cpp <- function(n, mean, sd, random_seed) {
  .Call(`_cpp11rng_sample_normal_std_cpp`, n, mean, sd, random_seed)
}

sample_normal_boost_cpp <- function(n, mean, sd, random_seed) {
  .Call(`_cpp11rng_sample_normal_boost_cpp`, n, mean, sd, random_seed)
}

sample_uniform_std_cpp <- function(n, min, max, random_seed) {
  .Call(`_cpp11rng_sample_uniform_std_cpp`, n, min, max, random_seed)
}

sample_uniform_boost_cpp <- function(n, min, max, random_seed) {
  .Call(`_cpp11rng_sample_uniform_boost_cpp`, n, min, max, random_seed)
}
